[tools]
goreleaser = "latest"
go = "latest"
changie = "latest"
"cargo:toon-format" = "latest"
"github:Dicklesworthstone/beads_rust" = "latest"
"github:Dicklesworthstone/beads_viewer" = "latest"

[tasks.release]
run = """
    changie batch auto
    changie merge
    git add CHANGELOG.md .changes/
    git commit -m "build(release): bump version to $(changie latest)"
    git tag $(changie latest)
    git push origin $(changie latest)
"""
