name: release

on:
  push:
    tags:
      - "v*-improved"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Install changie
        run: go install github.com/miniscruff/changie@latest
      - name: Resolve changie version
        run: echo "CHANGIE_LATEST=$(changie latest)" >> "$GITHUB_ENV"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean --release-notes ".changes/${{ env.CHANGIE_LATEST }}.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
